config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages
  post :lost_script, to: 'messages#lost_script'
  get :admin, to: 'messages#admin'
  get :doctor, to: 'messages#doctor'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :inbox
  belongs_to :outbox

  validates :body, :outbox_id, :inbox_id, presence: true

  LOST_MESSAGE = "I've lost my script, please issue a new one at a charge of €10"

  class << self
    def lost_message
      LOST_MESSAGE
    end
  end

end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Errors
end

app/controllers/concerns/errors.rb
module Errors
    extend ActiveSupport::Concern

    included do
      rescue_from(StandardError) { |e| handle_exception(e) }
    end

    private

    def handle_exception(e)
      case e
      when ActiveRecord::RecordNotFound
        error_response('record not found')
      when ActionController::ParameterMissing, KeyError
        error_response('parameter missing')
      else
        raise
      end
    end

    def error_response(error_messages, as_json = false)
      errors = case error_messages
      when ActiveRecord::Base
        ErrorSerializer.from_model(error_messages)
      else
        ErrorSerializer.from_messages(error_messages)
      end

      if as_json
        render json: errors, status: :unprocessable_entity
      else
        flash[:errors] = errors
        redirect_back(fallback_location: '/')
      end
    end
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def admin
    user = User.default_admin

    @inbox_messages = user.inbox.messages
  end

  def doctor
    user = User.default_doctor

    @inbox_messages = user.inbox.messages
    @outbox_messages = user.outbox.messages
    @unreaded_messages ||= user.inbox.unread_messages_count
  end

  def index
    user = User.current

    @inbox_messages = user.inbox.messages
  end

  def show
    @message = Message.find(params[:id])
    Messages::ReadService.call(@message) unless @message.read
  end

  def new
    @message = Message.new
  end

  def create
    result = Messages::CreateService.call(
      user_id: message_params[:user_id],
      body: message_params[:body],
      original_message_id: message_params[:original_message_id]
    )

    if result.success?
      redirect_to root_path
    else
      error_response(result.message)
    end
  end

  def lost_script
    result = Messages::CreateService.call(
      user_id: message_params[:user_id],
      original_message_id: message_params[:original_message_id],
      lose_script: true
    )

    return error_response(result.message, true) if result.failure?
    payment = Payments::CreateService.call(
      user_id: message_params[:user_id]
    )

    if payment.success?
      render json: payment.payment, status: :created
    else
      error_response(payment.errors, true)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :original_message_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/admin.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div>
        <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
    </div>
  <% @inbox_messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/doctor.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div style="display: flex; flex-direction: row">
        <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
        <p style="margin-left: 10%;"> <%= @unreaded_messages %> </p>
    </div>
  <% @inbox_messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>

  <h6 class="border-bottom border-gray pb-2 mb-0">Outbox</h6>
  <% @outbox_messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>



  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
  <% @inbox_messages.each do |message| %>
    <%= link_to message do %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(45) %>
        </p>
      </div>
    <% end %>
  <% end %>

  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>
  <% if flash[:errors] %>
    <%= flash[:errors] %>
  <% end %>

  <div class="card-body">
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>
      <%= f.hidden_field :original_message_id, value: params[:original_message_id] %>
      <%= f.hidden_field :user_id, value: params[:user_id] %>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <% if flash[:errors] %>
    <%= flash[:errors] %>
  <% end %>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <%= link_to "Reply", new_message_path(original_message_id: params[:id], user_id: @message.inbox.user_id),  class: "btn btn-primary" %>
    <a href="" id="requestScript" class="btn btn-primary">I've lost my prescription</a>
  </div>
</div>

<script>
  document.querySelector("#requestScript").addEventListener('click', () => {
    $.ajax({
        type: "POST",
        dataType: "json",
        data: {
          message: {
            original_message_id: <%= params[:id] %>,
            user_id: <%= @message.inbox.user_id %>
          }
        },
        url: "/lost_script",
        success: function(data){
          window.alert('Payment created')
        },
        error: function(err) {
          console.log(err)
          window.alert(err.responseJSON.errors[0].detail)
        }
    })
  })
</script>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>